# Regenerated on EVERY build (cheap): writes GitVersion.h with the exact
# `git describe` of the working tree, so any binary can say which commit it
# was built from (e.g. "v0.92-7-ga6a8118", "-dirty" when uncommitted).
# Only rewrites the header when the value changed, so no rebuild churn.
execute_process(
    COMMAND git -C "${SRC_DIR}" describe --tags --always --dirty
    OUTPUT_VARIABLE NS_GIT_DESCRIBE
    OUTPUT_STRIP_TRAILING_WHITESPACE
    ERROR_QUIET
    RESULT_VARIABLE NS_GIT_RC)
if(NOT NS_GIT_RC EQUAL 0 OR NS_GIT_DESCRIBE STREQUAL "")
    set(NS_GIT_DESCRIBE "unknown")
endif()
set(CONTENT "// Generated by cmake/GitVersion.cmake — do not edit.
#pragma once
#define NS_GIT_DESCRIBE \"${NS_GIT_DESCRIBE}\"
")
if(EXISTS "${OUT}")
    file(READ "${OUT}" OLD)
else()
    set(OLD "")
endif()
if(NOT OLD STREQUAL CONTENT)
    file(WRITE "${OUT}" "${CONTENT}")
endif()
